### PR TITLE
revert changes which can be packaged

### PR DESCRIPTION
**Pull request by maurerle**
This reverts the two vpn provider related patches, which are not required when using `gluon-mesh-vpn-parker` or `ffbs-mesh-vpn-parker` from https://github.com/SmithChart/community-packages/compare/topic/parker...ffac:community-packages:parker

### CODE REVIEW

**Comment by SmithChart** [comment]
please rebase

**Comment by maurerle** [comment]
I would rather force-push the v2023.2.x-parker branch to drop those two patches.

This PR was meant to test this concept and it seems that it works fine with the latest ffbs-mesh-vpn-parker package

**Comment by maurerle** [comment]
I added staging removals.
When building parker with the changes from these two pull-requests, everything should be working fine:
https://github.com/SmithChart/community-packages/pull/2
https://github.com/SmithChart/community-packages/pull/3

This should be the next thing to test

**Comment by SmithChart** [comment]
> I would rather force-push the v2023.2.x-parker branch to drop those two patches.
> 
> This PR was meant to test this concept and it seems that it works fine with the latest ffbs-mesh-vpn-parker package

I would prefer a force-push instead of reverting, too. If you are interested I can give you access to this repo.

**Comment by SmithChart** [comment]
> I added staging removals. When building parker with the changes from these two pull-requests, everything should be working fine: [SmithChart/community-packages#2](https://github.com/SmithChart/community-packages/pull/2) [SmithChart/community-packages#3](https://github.com/SmithChart/community-packages/pull/3)
> 
> This should be the next thing to test

https://github.com/SmithChart/community-packages/pull/3 has been merged. Commits have been dropped.
https://github.com/SmithChart/community-packages/pull/2 has discussion going on.

**Comment by SmithChart** [comment]
https://github.com/SmithChart/community-packages/pull/2 has been merged.

**Comment by SmithChart** [comment]
I have cherry-picked a0a5f166528e813f0f8cbe15f57a5fe88822d76d and f969b5e56cffae98b822140c445d108e393d901e and will squash them into the corresponding commits later on.
2870d72c6371bc945aca73902fa2a88b92fe8b8d already been applied.

@maurerle Please check if I've integrated it all correctly. Feel free to close if it looks good :-)

**Pull request closed without merging**
